apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-gabriel-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabszs/portfolio-web.git
    path: k8s
    targetRevision: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
