name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: gateway_converter
  DOCKER_HUB_USERNAME: gabzsz

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)

    - name: Push the Docker image to Docker Hub
      run: |
        docker tag ${{ env.IMAGE_NAME }}:$(date +%s) ${{ env.DOCKER_HUB_USER }}/{{ env.IMAGE_NAME }}:latest
        docker push ${{ env.DOCKER_HUB_USER }}/{{ env.IMAGE_NAME }}:latest
