name: Production CI

on:
  push:
    branches: [ "main" ]

env:
    IMAGE_NAME: gabzsz/portfolio-web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from package-lock.json
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package-lock.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Checkout GitOps Branch
        run: |
          git fetch origin
          git checkout gitops

      - name: Update Image Tag in Deployment
        run: |
          sed -i "s|image: gabzsz/portfolio-web:.*|image: gabzsz/portfolio-web:${{ env.VERSION }}|" k8s/deployment.yaml

      - name: Git Config
        run: |
          git config --global user.email "ci-bot@ci.com"
          git config --global user.name "CI Bot"

      - name: Commit and Push Changes
        run: |
          git add k8s/deployment.yaml
          git commit -m "Updating the image tag: ${VERSION}"
          git push origin gitops

      - name: Trigger Portainer Webhook
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
