name: Production CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: gateway_converter
  DOCKER_HUB_USERNAME: gabzsz

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image
      id: build-image
      env:
        IMAGE_NAME: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
        TIMESTAMP_TAG: $(date +%s)
      run: |
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TIMESTAMP_TAG .

    - name: Docker Images
      run: docker images

    - name: Tag and Push Docker Image to Docker Hub
      run: |
        docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }} --all-tags
